sites:
    - http://wanghuanming.com
    - http://ruanyifeng.com
    - http://coolshell.cn
    - http://andrewliu.tk
    - https://byvoid.com
    - http://www.wutianqi.com
    - http://blog.codingnow.com
    - http://blog.hesey.net
    - http://wuchong.me
    - http://blog.zhaojie.me
    - http://csrd.aliapp.com
    - http://airtrack.me
    - http://csrd.aliapp.com
